name: PR
on:
  pull_request:
  push:
    branches: [ ascdk-dev ]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test:chain']
    name: ${{ matrix.step }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install wheel
        python -m pip install pytest
    - name: Install EOS test framework
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        python -m pip install ipyeos
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
